name: Espresso Docker Build

on:
  push:
    branches:
      - integration
      - release-*
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow  }}-${{ github.ref  }}
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64,amd64

      - name: Setup Docker BuildKit
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Repo
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner  }}
          password: ${{ secrets.GITHUB_TOKEN  }}

      - name: Generate Docker Metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/EspressoSystems/arbitrum-token-bridge

      - name: Build and Push Docker
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request'  }}
          tags: ${{ steps.meta.outputs.tags  }}
          labels: ${{ steps.meta.outputs.labels  }}
          build-args: |
            NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=${{ vars.NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID }}
